name = "GuerreDesClans"
author = "Anhgelus Morhtuuzh"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73817358b8daa3b2e42894045941c05a39a5511c37b18602e49f356ba826cd7"

[versions]
fabric = "0.14.9"
minecraft = "1.19.1"

[options]
acceptable-game-versions = ["1.19"]
