name = "GuerreDesClans"
author = "Anhgelus Morhtuuzh"
version = "0.6.2-server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96856bc859087b33a06c4da1d2d112cfe7e221d1cb444429f0713d0594513e96"

[versions]
fabric = "0.14.9"
minecraft = "1.19.1"

[options]
acceptable-game-versions = ["1.19"]
