name = "GuerreDesClans"
author = "Anhgelus Morhtuuzh"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca5475fb98d6c16f25a670b8f3a5c4a9b2935f94e155339fc07507eb927e90c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.1"

[options]
acceptable-game-versions = ["1.19"]
